### ISSUE TITLE
constants_pb2

### ISSUE THREAD

**Issue by mwei2018** [PowerSpikeGG/PowerSpikeGG#129]
from powerspikegg.rawdata.public import constants_pb2

Is this constants_pb2 and this third party python library?

**Comment by FunkySayu** [comment]
Hi,

No. This is a custom protocol buffer we defined for our own project. You can find it there:
https://github.com/PowerSpikeGG/PowerSpikeGG/blob/develop/powerspikegg/rawdata/public/constants.proto
Compilation rule producing the constants_pb2 is available here:
https://github.com/PowerSpikeGG/PowerSpikeGG/blob/c688450d44e2dd7afbd34ce3b3561e7cf04b02b4/powerspikegg/rawdata/public/BUILD#L6

**Comment by mwei2018** [comment]
HI Axel,

Is it possible to implement mongondb's public query class in this way?

Thanks，
Mason
________________________________
发件人: Axel Martin <notifications@github.com>
发送时间: Saturday, July 27, 2019 1:53:33 AM
收件人: PowerSpikeGG/PowerSpikeGG <PowerSpikeGG@noreply.github.com>
抄送: Mason <wybztn@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [PowerSpikeGG/PowerSpikeGG] constants_pb2 (#129)


Closed #129<https://github.com/PowerSpikeGG/PowerSpikeGG/issues/129>.

―

**Comment by ArchangelX360** [comment]
@mwei2018 would you mind to elaborate on what is a 

> MongoDB's public query class
