### ISSUE TITLE
Manage docker image compilation through Bazel

### ISSUE THREAD

**Issue by FunkySayu** [PowerSpikeGG/PowerSpikeGG#44]

**Comment by cassand** [comment]
It seems on a good way.

Here is the current state :
- [ ] Fetcher : https://github.com/PowerSpikeGG/PowerSpikeGG/pull/51
- [ ] Gateway : https://github.com/PowerSpikeGG/PowerSpikeGG/pull/53
- [ ] Front : To be done
- [ ] MongoDB :  https://github.com/PowerSpikeGG/PowerSpikeGG/pull/51

**Comment by FunkySayu** [comment]
Closed by #75
