### ISSUE TITLE
Gazelle script sed

### ISSUE THREAD

**Issue by ArchangelX360** [PowerSpikeGG/PowerSpikeGG#57]
sed -i seemed not to work correctly

     "//powerspikegg/rawdata/public/leagueoflegends_gopb:go_default_library",

should be 

     "//powerspikegg/rawdata/public:leagueoflegends_gopb",

**Comment by FunkySayu** [comment]
@ArchangelX360 TAKE DIS

**Comment by ArchangelX360** [comment]
#74 fix that
