### ISSUE TITLE
Aggregate average statistics on many matches

### ISSUE THREAD

**Issue by FunkySayu** [PowerSpikeGG/PowerSpikeGG#65]
Stats that should be aggregated:

			"stats" : {
				"largestCriticalStrike" : 694,
				"totalDamageDealt" : 66330,
				"magicDamageDealtToChampions" : 0,
				"largestMultiKill" : 2,
				"largestKillingSpree" : 4,
				"quadraKills" : 0,
				"magicDamageTaken" : 2406,
				"towerKills" : 2,
				"totalTimeCrowdControlDealt" : 21,
				"neutralMinionsKilledEnemyJungle" : 0,
				"neutralMinionsKilledTeamJungle" : 0,
				"wardsKilled" : 2,
				"physicalDamageDealt" : 66050,
				"wardsPlaced" : 4,
				"minionsKilled" : 128,
				"tripleKills" : 0,
				"champLevel" : 11,
				"magicDamageDealt" : 0,
				"kills" : 7,
				"doubleKills" : 1,
				"trueDamageTaken" : 0,
				"assists" : 5,
				"deaths" : 3,
				"neutralMinionsKilled" : 0,
				"visionWardsBoughtInGame" : 0,
				"physicalDamageDealtToChampions" : 11032,
				"goldSpent" : 8900,
				"trueDamageDealt" : 280,
				"trueDamageDealtToChampions" : 0,
				"pentaKills" : 0,
				"totalHeal" : 1827,
				"goldEarned" : 9710,
				"sightWardsBoughtInGame" : 0,
				"totalDamageDealtToChampions" : 11032,
				"totalUnitsHealed" : 2,
				"inhibitorKills" : 0,
				"totalScoreRank" : 0,
				"totalDamageTaken" : 10782,
				"killingSprees" : 2,
				"physicalDamageTaken" : 8375
			},

**Comment by ArchangelX360** [comment]
#70 should implement that.
