### ISSUE TITLE
Summoner name needed in participant champion

### ISSUE THREAD

**Issue by ArchangelX360** [PowerSpikeGG/PowerSpikeGG#94]
// Champion. Conversion to named entities is provided by the Riot API.
message Champion {
    int32 id = 1;
    **string name = 2;**
}

**Comment by ArchangelX360** [comment]
timestamp of first tower kill also

**Comment by FunkySayu** [comment]
Fixed by #95. First tower kill is not available for now, since it requires the timeline data.
